// <auto-generated />
using System;
using LuxRentals.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuxRentals.Migrations
{
    [DbContext(typeof(LuxRentalExperimentalContext))]
    [Migration("20260206233051_InitialIdentitySetup")]
    partial class InitialIdentitySetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuxRentals.Models.Booking", b =>
                {
                    b.Property<int>("PkBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkBookingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkBookingId"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancelledAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("endDateTime");

                    b.Property<int>("FkBookingStatusId")
                        .HasColumnType("int")
                        .HasColumnName("fkBookingStatusId");

                    b.Property<int>("FkCarId")
                        .HasColumnType("int")
                        .HasColumnName("fkCarId");

                    b.Property<int>("FkCustomerId")
                        .HasColumnType("int")
                        .HasColumnName("fkCustomerId");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("startDateTime");

                    b.HasKey("PkBookingId")
                        .HasName("PK__Booking__8A399DE04656770F");

                    b.HasIndex("FkBookingStatusId");

                    b.HasIndex("FkCarId");

                    b.HasIndex("FkCustomerId");

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("LuxRentals.Models.BookingStatus", b =>
                {
                    b.Property<int>("PkBookingStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkBookingStatusId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkBookingStatusId"));

                    b.Property<string>("BookingStatus1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("bookingStatus");

                    b.HasKey("PkBookingStatusId")
                        .HasName("PK__BookingS__9B31AD42926FE053");

                    b.ToTable("BookingStatus", (string)null);
                });

            modelBuilder.Entity("LuxRentals.Models.Car", b =>
                {
                    b.Property<int>("PkCarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkCarId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkCarId"));

                    b.Property<string>("CarThumbnail")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("carThumbnail");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("colour");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(19, 2)")
                        .HasColumnName("dailyRate");

                    b.Property<int>("FkCarStatusId")
                        .HasColumnType("int")
                        .HasColumnName("fkCarStatusId");

                    b.Property<int>("FkFuelTypeId")
                        .HasColumnType("int")
                        .HasColumnName("fkFuelTypeId");

                    b.Property<int>("FkModelId")
                        .HasColumnType("int")
                        .HasColumnName("fkModelId");

                    b.Property<int>("FkVehicleClassId")
                        .HasColumnType("int")
                        .HasColumnName("fkVehicleClassId");

                    b.Property<string>("LicencePlate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("licencePlate");

                    b.Property<int>("LuggageCap")
                        .HasColumnType("int")
                        .HasColumnName("luggageCap");

                    b.Property<int>("PersonCap")
                        .HasColumnType("int")
                        .HasColumnName("personCap");

                    b.Property<byte>("TransmissionType")
                        .HasColumnType("tinyint")
                        .HasColumnName("transmissionType");

                    b.Property<string>("VinNumber")
                        .IsRequired()
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("vinNumber");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("PkCarId")
                        .HasName("PK__Car__042F2AAC8C207229");

                    b.HasIndex("FkCarStatusId");

                    b.HasIndex("FkFuelTypeId");

                    b.HasIndex("FkModelId");

                    b.HasIndex("FkVehicleClassId");

                    b.HasIndex(new[] { "LicencePlate" }, "UQ__Car__1771C83D32098E36")
                        .IsUnique();

                    b.HasIndex(new[] { "VinNumber" }, "UQ__Car__96F3ADF4CF09D564")
                        .IsUnique();

                    b.ToTable("Car", (string)null);
                });

            modelBuilder.Entity("LuxRentals.Models.CarStatus", b =>
                {
                    b.Property<int>("PkCarStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkCarStatusId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkCarStatusId"));

                    b.Property<string>("StatusFlag")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("statusFlag");

                    b.HasKey("PkCarStatusId")
                        .HasName("PK__CarStatu__18420CBDF71FC4AD");

                    b.ToTable("CarStatus", (string)null);
                });

            modelBuilder.Entity("LuxRentals.Models.Customer", b =>
                {
                    b.Property<int>("PkCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkCustomerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkCustomerId"));

                    b.Property<string>("DriverLicenceNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("driverLicenceNo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("lastName");

                    b.Property<bool?>("LicenceVerified")
                        .HasColumnType("bit")
                        .HasColumnName("licenceVerified");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phoneNumber");

                    b.HasKey("PkCustomerId")
                        .HasName("PK__Customer__1FD9D5A21845FCB4");

                    b.HasIndex(new[] { "DriverLicenceNo" }, "UQ__Customer__021FFF57F2588E48")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Customer__AB6E6164D14DE559")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("LuxRentals.Models.FuelType", b =>
                {
                    b.Property<int>("PkFuelTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkFuelTypeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkFuelTypeId"));

                    b.Property<string>("FuelType1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fuelType");

                    b.HasKey("PkFuelTypeId")
                        .HasName("PK__FuelType__8BECB883228BC67B");

                    b.ToTable("FuelType", (string)null);
                });

            modelBuilder.Entity("LuxRentals.Models.Make", b =>
                {
                    b.Property<int>("PkMakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkMakeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkMakeId"));

                    b.Property<string>("MakeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("makeName");

                    b.HasKey("PkMakeId")
                        .HasName("PK__Make__DCFC4DDA58E2E141");

                    b.ToTable("Make", (string)null);
                });

            modelBuilder.Entity("LuxRentals.Models.Model", b =>
                {
                    b.Property<int>("PkModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkModelId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkModelId"));

                    b.Property<int>("FkMakeId")
                        .HasColumnType("int")
                        .HasColumnName("fkMakeId");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modelName");

                    b.HasKey("PkModelId")
                        .HasName("PK__Model__C59EF50784A88CAE");

                    b.HasIndex("FkMakeId");

                    b.ToTable("Model", (string)null);
                });

            modelBuilder.Entity("LuxRentals.Models.Transaction", b =>
                {
                    b.Property<int>("PkTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkTransactionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkTransactionId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(19, 2)")
                        .HasColumnName("amountPaid");

                    b.Property<int>("FkBookingId")
                        .HasColumnType("int")
                        .HasColumnName("fkBookingId");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("paymentDate");

                    b.HasKey("PkTransactionId")
                        .HasName("PK__Transact__D3354406B02BEB62");

                    b.HasIndex("FkBookingId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("LuxRentals.Models.VehicleClass", b =>
                {
                    b.Property<int>("PkVehicleClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pkVehicleClassId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkVehicleClassId"));

                    b.Property<string>("VehicleClass1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vehicleClass");

                    b.HasKey("PkVehicleClassId")
                        .HasName("PK__VehicleC__0B88CBFEE83AAA95");

                    b.ToTable("VehicleClass", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LuxRentals.Models.Booking", b =>
                {
                    b.HasOne("LuxRentals.Models.BookingStatus", "FkBookingStatus")
                        .WithMany("Bookings")
                        .HasForeignKey("FkBookingStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Status");

                    b.HasOne("LuxRentals.Models.Car", "FkCar")
                        .WithMany("Bookings")
                        .HasForeignKey("FkCarId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Car");

                    b.HasOne("LuxRentals.Models.Customer", "FkCustomer")
                        .WithMany("Bookings")
                        .HasForeignKey("FkCustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Customer");

                    b.Navigation("FkBookingStatus");

                    b.Navigation("FkCar");

                    b.Navigation("FkCustomer");
                });

            modelBuilder.Entity("LuxRentals.Models.Car", b =>
                {
                    b.HasOne("LuxRentals.Models.CarStatus", "FkCarStatus")
                        .WithMany("Cars")
                        .HasForeignKey("FkCarStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Car_CarStatus");

                    b.HasOne("LuxRentals.Models.FuelType", "FkFuelType")
                        .WithMany("Cars")
                        .HasForeignKey("FkFuelTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Car_FuelType");

                    b.HasOne("LuxRentals.Models.Model", "FkModel")
                        .WithMany("Cars")
                        .HasForeignKey("FkModelId")
                        .IsRequired()
                        .HasConstraintName("FK_Car_Model");

                    b.HasOne("LuxRentals.Models.VehicleClass", "FkVehicleClass")
                        .WithMany("Cars")
                        .HasForeignKey("FkVehicleClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Car_VehicleClass");

                    b.Navigation("FkCarStatus");

                    b.Navigation("FkFuelType");

                    b.Navigation("FkModel");

                    b.Navigation("FkVehicleClass");
                });

            modelBuilder.Entity("LuxRentals.Models.Model", b =>
                {
                    b.HasOne("LuxRentals.Models.Make", "FkMake")
                        .WithMany("Models")
                        .HasForeignKey("FkMakeId")
                        .IsRequired()
                        .HasConstraintName("FK_Model_Make");

                    b.Navigation("FkMake");
                });

            modelBuilder.Entity("LuxRentals.Models.Transaction", b =>
                {
                    b.HasOne("LuxRentals.Models.Booking", "FkBooking")
                        .WithMany("Transactions")
                        .HasForeignKey("FkBookingId")
                        .IsRequired()
                        .HasConstraintName("FK_Transaction_Booking");

                    b.Navigation("FkBooking");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuxRentals.Models.Booking", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("LuxRentals.Models.BookingStatus", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("LuxRentals.Models.Car", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("LuxRentals.Models.CarStatus", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("LuxRentals.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("LuxRentals.Models.FuelType", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("LuxRentals.Models.Make", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("LuxRentals.Models.Model", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("LuxRentals.Models.VehicleClass", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
