using LuxRentals.Data;
using LuxRentals.ViewModels;
using LuxRentals.ViewModels.Roles;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;

namespace LuxRentals.Repositories.Roles
{
    public class RoleRepo
    {
        private readonly LuxRentalsDbContext _db;
        private readonly ILogger<RoleRepo> _logger;

        public RoleRepo(LuxRentalsDbContext context, ILogger<RoleRepo> logger)
        {
            _db = context;
            _logger = logger;
        }

        // Return a list of Role Viewmodel records
        public List<RoleVm> GetAllRoles()
        {
            return _db.Roles
                .Select(r => new RoleVm
                {
                    Id = r.Id,
                    RoleName = r.Name
                })
                .ToList();
        }

        // Return a single Viewmodel record.
        public RoleVm? GetRole(string roleId)
        {
            var role = _db.Roles.FirstOrDefault(r => r.Id == roleId);
            if (role != null)
            {
                return new RoleVm
                {
                    Id = role.Id,
                    RoleName = role.Name
                };
            }

            return null;
        }

        // Create a new role record.
        public bool CreateRole(string roleName)
        {
            try
            {
                // Normalize name
                string normalizedName = roleName.ToUpperInvariant();

                // Check if role name already exists
                bool roleExists = _db.Roles.Any(r => r.NormalizedName == normalizedName);

                if (roleExists)
                {
                    _logger.LogInformation("CreateRole: role '{RoleName}' already exists", roleName);
                    return false;
                }

                _db.Roles.Add(new IdentityRole
                {
                    Name = roleName,
                    NormalizedName = normalizedName
                    // Id will be generated by EF/Identity
                });

                _db.SaveChanges();
                return true;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating role '{RoleName}'", roleName);
                return false;
            }
        }
    }
}
