using LuxRentals.Data;
using LuxRentals.ViewModels;
using LuxRentals.ViewModels.Roles;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace LuxRentals.Repositories.Roles
{
    public class RoleRepo
    {
        private readonly LuxRentalsDbContext _db;
        private readonly ILogger<RoleRepo> _logger;

        public RoleRepo(LuxRentalsDbContext context, ILogger<RoleRepo> logger)
        {
            _db = context;
            _logger = logger;
        }

        // Return a list of Role Viewmodel records
        public async Task <List<RoleVm>> GetAllRolesAsync()
        {
            return await _db.Roles
                .Select(r => new RoleVm
                {
                    Id = r.Id,
                    RoleName = r.Name
                })
                .ToListAsync();
        }

        // Return a single Viewmodel record.
        public async Task<RoleVm?> GetRoleAsync(string roleId)
        {
            var role = await _db.Roles.FirstOrDefaultAsync(r => r.Id == roleId);
            if (role != null)
            {
                return new RoleVm
                {
                    Id = role.Id,
                    RoleName = role.Name
                };
            }

            return null;
        }

        // Create a new role record.
        public async Task<bool> CreateRoleAsync(string roleName)
        {
            try
            {
                // Normalize name
                string normalizedName = roleName.ToUpperInvariant();

                // Check if role name already exists
                bool roleExists = await _db.Roles.AnyAsync(r => r.NormalizedName == normalizedName);

                if (roleExists)
                {
                    _logger.LogInformation("CreateRole: role '{RoleName}' already exists", roleName);
                    return false;
                }

                await _db.Roles.AddAsync(new IdentityRole
                {
                    Name = roleName,
                    NormalizedName = normalizedName
                    // Id will be generated by EF/Identity
                });

                await _db.SaveChangesAsync();
                return true;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating role '{RoleName}'", roleName);
                return false;
            }
        }

        // Delete a role
        public async Task<bool> DeleteRoleAsync(string roleId)
        {
            try
            {
                var role = await _db.Roles.FindAsync(roleId);
                if (role == null)
                {
                    return false;
                }

                // Check if role is in use
                bool roleInUse = await _db.UserRoles.AnyAsync(ur => ur.RoleId == roleId);
                if (roleInUse)
                {
                    _logger.LogInformation("DeleteRole: role {RoleId} is in use and cannot be deleted", roleId);
                    return false;
                }

                _db.Roles.Remove(role);
                await _db.SaveChangesAsync();
                return true;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error deleting role {RoleId}", roleId);
                return false;
            }
        }

    }
}
